[package]
name = "cw-merkle-tree"
version = "0.1.0"
edition = "2021"

[dependencies]
cosmwasm-std = "1.1.3"
cw-storage-plus = "0.15.1"
serde = { version = "1.0.145", default-features = false, features = ["derive"] }
thiserror = "1.0.37"

[dev-dependencies]
blake2 = "0.10.4"
